### ISSUE TITLE
have update?

### ISSUE THREAD

**Issue by jamilservicos** [exlcode/exlcode#2]
is there an update of this project?

**Comment by svarlamov** [comment]
@jamilservicos Hi there, most of this work has moved over to https://codingrooms.com. Are you using the Chrome extension at the moment?

**Comment by jamilservicos** [comment]
> @jamilservicos Hi there, most of this work has moved over to https://codingrooms.com. Are you using the Chrome extension at the moment?

I'm not using it right now.
I found the project in a survey and found it interesting.
too bad it became something commercial, as it would be very useful for many people.
